
const diseases = [
    {
        image: 'images/mangoanthracnose.jpg',
        name: 'Mango Anthracnose',
        description: 'Mango anthracnose, caused by the fungus Colletotrichum gloeosporioides, is a common and destructive disease affecting mango trees globally. It primarily manifests as dark, sunken lesions on mango fruit, leaves, and stems.',
        symptoms: 'Symptoms of mango anthracnose initially appear as small, water-soaked spots on young fruits and leaves. As the disease progresses, these spots enlarge and darken, forming characteristic sunken lesions with distinct margins. Severely affected fruits may become distorted and drop prematurely, leading to significant yield losses.',
        causes: 'The fungus Colletotrichum gloeosporioides thrives in warm, humid conditions and spreads through airborne spores, rain splash, and contaminated pruning tools. Infection is favored by wounds on fruit and foliage, as well as prolonged leaf wetness.',
        management: 'Integrated disease management strategies are crucial for controlling mango anthracnose. Cultural practices such as removing and destroying infected plant debris, promoting good orchard sanitation, and avoiding overhead irrigation can help reduce disease pressure. Additionally, applying fungicides during early flowering and fruit set can suppress disease development.',
        medicines: 'Apply fungicides like copper or mancozeb during early flowering and fruit set to suppress disease development.',
        precautions: 'Practice good sanitation by removing and destroying infected plant debris. Implement cultural practices to minimize plant stress and avoid injuring fruit and foliage. Ensure proper spacing between trees to promote air circulation and reduce humidity levels.'
    },
    {
        image: 'images/mangobacterialcanker.jpg',
        name: 'Mango Bacterial Canker',
        description: 'Mango bacterial canker, caused by the bacterium Xanthomonas campestris pv. mangiferae, is a devastating disease affecting mango trees worldwide. It primarily affects leaves, stems, and fruits, leading to significant economic losses in mango production.',
        symptoms: 'Symptoms of mango bacterial canker include water-soaked lesions on leaves, stems, and fruits, which later turn brown or black as they enlarge. Lesions may exude bacterial ooze under high humidity conditions. Infected leaves may also exhibit yellowing and premature defoliation.',
        causes: 'The bacterium Xanthomonas campestris pv. mangiferae spreads through rain splash, wind, and contaminated pruning tools. Infection is favored by warm, humid weather and wounds on plant tissue, such as those caused by pruning or insect feeding.',
        management: 'Effective management of mango bacterial canker involves cultural and chemical control measures. Cultural practices include pruning and removing infected plant parts, promoting good orchard hygiene, and avoiding excessive plant stress. Additionally, copper-based bactericides can be applied to suppress disease spread.',
        medicines: 'Copper-based bactericides such as copper hydroxide or copper oxychloride can be used to control the disease.',
        precautions: 'To minimize disease spread, avoid injuring the plant during cultivation and maintain good orchard sanitation. Implement preventive measures such as proper irrigation and avoiding excessive fertilization. Regular monitoring for symptoms and early intervention are essential for effective disease management.'
    },
    {
        image: 'images/mangocuttingweevil.jpg',
        name: 'Mango Cutting Weevil',
        description: 'The mango cutting weevil (Sternochetus mangiferae) is a destructive pest that primarily targets mango seeds, causing significant damage to developing fruits. This weevil species is a serious threat to mango cultivation in many regions.',
        symptoms: 'Infestation by mango cutting weevils typically results in the presence of small holes or entry wounds on mango fruits. Larvae of the weevil bore into the seeds, feeding on the internal tissues and causing them to rot. Infested fruits may exhibit signs of premature ripening, decay, or internal damage.',
        lifeCycle: 'The life cycle of the mango cutting weevil consists of four stages: egg, larva, pupa, and adult. Adult weevils lay eggs inside mango fruits, and upon hatching, the larvae tunnel into the seeds for feeding and development. After completing their development, mature larvae pupate within the seeds, eventually emerging as adult weevils.',
        management: 'Effective management of mango cutting weevils involves a combination of cultural, biological, and chemical control methods. Cultural practices such as sanitation, proper orchard hygiene, and removal of fallen and infested fruits can help reduce weevil populations. Biological control agents, such as natural predators and parasitoids, may also play a role in suppressing weevil infestations. Additionally, chemical control measures using insecticides like carbaryl or endosulfan can be applied to target adult weevils and prevent further damage to mango fruits.',
        medicines: 'To control adult weevils, use insecticides like carbaryl or endosulfan. Apply the insecticides according to recommended dosage and timing for effective suppression of weevil populations.',
        precautions: 'To minimize weevil infestations, implement preventive measures such as regular monitoring of orchards for signs of infestation, timely removal and destruction of fallen and infested fruits, and proper sanitation practices. Avoid excessive use of insecticides and adhere to integrated pest management (IPM) principles to maintain ecological balance in the orchard ecosystem.'
    },
    {
        image: 'images/mangodieback.jpg',
        name: 'Mango Die Back',
        description: 'Mango dieback is a physiological disorder characterized by the progressive death and decline of the tips of mango branches. While dieback can result from various factors, including environmental stressors and cultural practices, fungal infections are often implicated in its development.',
        symptoms: 'Symptoms of mango dieback typically manifest as the wilting, browning, and eventual death of the terminal shoots and branches of mango trees. Affected branches may exhibit dieback symptoms gradually, with tip dieback progressing inward toward the main trunk. In severe cases, dieback can lead to significant canopy thinning and reduced fruit production.',
        causes: 'The development of mango dieback can be attributed to multiple factors, including fungal pathogens such as Botryosphaeria spp. and Colletotrichum gloeosporioides, as well as abiotic stressors like drought, waterlogging, nutrient deficiencies, and improper pruning or training techniques. Fungal infections weaken the plants natural defenses, making it more susceptible to dieback.',
        management: 'Management of mango dieback involves a holistic approach addressing both the underlying causes and symptomatic treatment. Cultural practices such as proper irrigation, balanced fertilization, and pruning to remove infected branches can help mitigate stressors and reduce the likelihood of dieback development. Additionally, timely application of fungicides containing active ingredients like copper oxychloride or carbendazim can suppress fungal pathogens and prevent further spread of the disease.',
        medicines: 'Treat mango dieback with fungicides like copper oxychloride or carbendazim. Apply the fungicides according to recommended dosage and timing for effective disease control and symptom alleviation.',
        precautions: 'To minimize the risk of mango dieback, implement preventive measures such as maintaining optimal orchard conditions, including adequate irrigation, drainage, and nutrition. Practice proper pruning techniques to promote airflow and reduce moisture retention in the canopy. Monitor trees regularly for signs of stress or disease, and take prompt action to address any issues that arise.'
    },
    {
        image: 'images/mangogallmidge.jpg',
        name: 'Mango Gall Midge',
        description: 'The mango gall midge (Procontarinia mangiferae) is a destructive pest that infests mango trees, causing the formation of galls on leaves. These galls disrupt normal leaf function, leading to deformation and stunted growth in affected mango plants.',
        symptoms: 'Symptoms of mango gall midge infestation include the development of small, blister-like galls on mango leaves. These galls may vary in size and color, ranging from green to reddish-brown, and often cause distortion or curling of affected leaves. Severe infestations can result in widespread gall formation, leading to reduced photosynthetic capacity and overall growth impairment in mango trees.',
        causes: 'Mango gall midges lay their eggs on young mango leaves, and upon hatching, the larvae feed on leaf tissues, stimulating the formation of galls as a protective habitat. The feeding activity of midge larvae within the galls disrupts normal leaf development and physiology, causing the characteristic symptoms associated with gall midge infestation.',
        management: 'Effective management of mango gall midge involves a combination of cultural, biological, and chemical control methods. Cultural practices such as pruning to remove infested leaves and promoting overall tree health can help reduce midge populations. Biological control agents, such as natural predators and parasitoids, may also play a role in suppressing midge infestations. Additionally, chemical control measures using insecticides like dimethoate or imidacloprid can be applied to target midge larvae and prevent further damage to mango leaves.',
        medicines: 'To manage mango gall midge infestations, use insecticides like dimethoate or imidacloprid. Apply the insecticides according to recommended dosage and timing for effective suppression of midge populations and gall formation.',
        precautions: 'To prevent the spread of mango gall midge infestations, implement preventive measures such as regular monitoring of mango trees for signs of gall formation, timely removal and destruction of infested leaves, and proper sanitation practices in the orchard.'
    },
    {
        image: 'images/mangohealthy.jpg',
        name: 'Mango Healthy',
        description: 'Mango plants in a healthy state exhibit vigorous growth and productivity, with no visible signs of diseases or pest infestations. Healthy mango trees are characterized by lush foliage, robust stems, and the absence of symptoms such as leaf discoloration, wilting, or deformities.',
        symptoms: 'No symptoms are associated with a healthy mango plant, as it is free from diseases and pest infestations.',
        causes: 'The health of mango plants is influenced by various factors, including environmental conditions, soil quality, cultural practices, and genetic factors. Adequate sunlight, water, and nutrients are essential for promoting healthy growth in mango trees. Proper care practices, such as regular watering, fertilization, and pruning, contribute to maintaining plant health and vigor.',
        management: 'Maintaining mango plant health primarily involves implementing proper care practices and preventive measures to address potential stressors and minimize the risk of disease or pest outbreaks. Regular inspections and monitoring of mango trees for signs of stress, nutrient deficiencies, or pest activity are essential for early detection and intervention. Timely implementation of cultural practices such as irrigation, fertilization, and pest management helps ensure optimal plant health and productivity.',
        medicine: 'No specific medicines are required for maintaining the health of mango plants, as they are naturally resilient and resistant to most diseases and pests when provided with proper care and growing conditions.',
        precautions: 'To promote and sustain mango plant health, adhere to recommended cultural practices, including proper irrigation, fertilization, and pruning. Monitor trees regularly for signs of stress or pest activity, and take prompt action to address any issues that arise.'
    },
    {
        image: 'images/mangopowderymildew.jpg',
        name: 'Mango Powdery Mildew',
        description: 'Mango powdery mildew is a fungal disease characterized by the formation of a white powdery layer on the surface of mango leaves, flowers, and fruits. This fungal growth can negatively impact mango plant health and reduce fruit quality if left untreated.',
        symptoms: 'Symptoms of mango powdery mildew include the development of a white, powdery fungal growth on the upper surfaces of mango leaves, flowers, and fruits. Infected plant parts may also exhibit stunted growth, leaf curling, and premature leaf drop. Severe infections can lead to reduced fruit yield and quality.',
        causes: 'Mango powdery mildew is caused by various species of fungi belonging to the Erysiphales order, such as Oidium mangiferae. The disease typically thrives in warm, humid conditions with poor air circulation, making mango orchards susceptible to powdery mildew outbreaks during periods of high humidity and temperature fluctuations.',
        management: 'Management of mango powdery mildew involves implementing cultural, biological, and chemical control measures to suppress fungal growth and prevent disease spread. Cultural practices such as pruning to improve air circulation, removing infected plant debris, and maintaining proper spacing between mango trees can help reduce disease pressure. Biological control agents, such as beneficial fungi or bacteria, may also be employed to inhibit powdery mildew development. Additionally, chemical control options using sulfur-based fungicides or potassium bicarbonate can effectively manage powdery mildew outbreaks when applied according to label instructions and integrated into a comprehensive disease management program.',
        medicines: 'To control mango powdery mildew, apply sulfur-based fungicides or potassium bicarbonate according to recommended dosage and timing. These fungicides can help suppress fungal growth and prevent further spread of the disease within the mango orchard.',
        precautions: 'To minimize the risk of mango powdery mildew outbreaks, improve air circulation within the orchard by pruning trees to reduce canopy density and remove any obstacles that may impede airflow. Additionally, avoid overhead irrigation and maintain adequate spacing between mango trees to promote ventilation and reduce humidity levels. Regularly monitor mango trees for signs of powdery mildew and implement timely interventions to prevent disease establishment and spread.'
    },
    {
        image: 'images/mangosootymould.jpg',
        name: 'Mango Sooty Mould',
        description: 'Mango sooty mould is a fungal growth characterized by a black, sooty coating on mango leaves and fruits, often associated with insect infestations. This fungal growth does not directly harm mango plants but can indirectly affect their health and reduce fruit quality by interfering with photosynthesis and attracting secondary pests.',
        symptoms: 'Symptoms of mango sooty mould include the presence of a black, sooty coating on the upper surfaces of mango leaves, stems, and fruits. Infected plant parts may appear discolored and may feel sticky to the touch due to the presence of honeydew secretions produced by sap-feeding insects such as aphids or scales. Severe infestations can lead to reduced photosynthetic activity, leaf yellowing, and premature leaf drop.',
        causes: 'Mango sooty mould is caused by the growth of saprophytic fungi such as various species of Capnodium or Cladosporium on the sugary honeydew secretions produced by sap-feeding insects like aphids, scales, or mealybugs. These fungi colonize the honeydew-coated surfaces of mango plants, forming a black, sooty layer that can inhibit sunlight penetration and interfere with plant metabolism.',
        management: 'Management of mango sooty mould involves addressing the underlying insect infestations responsible for honeydew production and implementing measures to reduce fungal growth and sooty mould development. Control of sap-feeding insects such as aphids or scales through cultural practices, biological control agents, or targeted insecticide applications can help prevent honeydew accumulation and subsequent sooty mould formation. Additionally, maintaining clean surroundings, removing infested plant debris, and managing insect populations effectively can help minimize the risk of mango sooty mould outbreaks in the orchard.',
        medicines: 'To control mango sooty mould, it is essential to address the underlying insect infestations responsible for honeydew production. Use insecticides targeted at sap-feeding insects like aphids or scales to reduce honeydew secretion and prevent sooty mould formation. Additionally, consider applying fungicides to affected plant parts to inhibit fungal growth and remove existing sooty mould deposits using gentle washing with water or mild soap solutions.',
        precautions: 'To prevent mango sooty mould infestations, monitor mango trees regularly for signs of sap-feeding insects such as aphids or scales and implement timely interventions to control their populations. Avoid over-fertilization or excessive use of nitrogen-based fertilizers, as these may promote lush vegetative growth and attract more sap-feeding pests. Implement good orchard sanitation practices, including the removal of infested plant debris and the maintenance of clean surroundings, to reduce the risk of sooty mould establishment and spread.'
    },
    {
        image: 'images/appleblackrot.jpg',
        name: 'Apple Black Rot',
        description: 'Apple black rot is a fungal disease that causes black, rot-like lesions on apples and leaves, leading to significant fruit loss and reduced orchard productivity. This disease is caused by the fungus Botryosphaeria obtusa and thrives in warm, humid conditions, making apple orchards susceptible to black rot outbreaks during periods of wet weather or high humidity.',
        symptoms: 'Symptoms of apple black rot include the development of circular, black, sunken lesions on apple fruits and leaves. These lesions often begin as small, water-soaked spots that gradually enlarge and become necrotic, leading to fruit decay and shriveling. Infected apples may also exhibit signs of fungal growth, such as dark, velvety spores on the surface of the lesions. Severe infections can result in widespread fruit rot, premature fruit drop, and defoliation, ultimately reducing orchard yield and fruit quality.',
        causes: 'Apple black rot is caused by the fungus Botryosphaeria obtusa, which infects apple trees through wounds or natural openings such as lenticels or stomata. The fungus produces spores that are dispersed by wind or rain, facilitating the spread of the disease within the orchard. Warm, humid conditions with prolonged wetness favor fungal growth and disease development, making apple orchards susceptible to black rot outbreaks during periods of high humidity or rainfall.',
        management: 'Management of apple black rot involves implementing integrated disease management strategies to minimize disease pressure and prevent fruit loss. Cultural practices such as pruning to improve air circulation, removing infected fruit and foliage, and maintaining proper orchard sanitation can help reduce disease inoculum and limit disease spread. Additionally, chemical control options using fungicides like captan or thiophanate-methyl can effectively suppress black rot outbreaks when applied according to recommended dosage and timing.',
        medicines: 'To control apple black rot, apply fungicides like captan or thiophanate-methyl according to recommended dosage and timing. These fungicides can help inhibit fungal growth and prevent further spread of the disease within the apple orchard.',
        precautions: 'To minimize the risk of apple black rot outbreaks'
    },
    {
        image: 'images/applehealthy.jpg',
        name: 'Apple Healthy',
        description: 'Apple healthy refers to the optimal state of an apple plant where there are no signs of diseases or pest infestations, and the plant is exhibiting robust growth and development. In this state, the apple tree is able to produce high-quality fruits and maintain overall orchard productivity.',
        symptoms: 'Symptoms of a healthy apple tree include vibrant green foliage, sturdy branches, and vigorous growth throughout the growing season. The absence of any abnormal discoloration, lesions, or deformities on the leaves, stems, or fruits indicates the plants health. Healthy apple trees typically exhibit balanced vegetative and reproductive growth, with adequate fruit set and development.',
        causes: 'Apple trees achieve and maintain a healthy state when provided with optimal growing conditions, including proper sunlight exposure, well-drained soil, adequate moisture levels, and appropriate nutrient availability. Healthy apple orchards also benefit from good cultural practices such as regular pruning, proper spacing between trees, and integrated pest management strategies to prevent disease and pest outbreaks.',
        management: 'Maintaining apple tree health requires ongoing monitoring, preventive measures, and timely interventions to address any emerging issues before they escalate into significant problems. Regular inspections of apple trees for signs of diseases, pests, or nutrient deficiencies allow growers to detect and mitigate potential threats early. Implementing standard care practices such as balanced fertilization, irrigation management, and weed control helps support apple tree health and vitality throughout the growing season.',
        medicines: 'No specific medicines are required for a healthy apple tree. However, routine applications of balanced fertilizers, micronutrient supplements, and organic soil amendments can promote tree vigor and enhance fruit quality. Additionally, preventive treatments such as dormant oil sprays or horticultural oils may be applied during dormancy to suppress overwintering pests and diseases and maintain orchard health.',
        precautions: 'To sustain the health of apple trees, continue implementing standard care practices including regular inspections, balanced fertilization, and irrigation management. Avoid excessive use of synthetic pesticides or chemical fertilizers that can disrupt soil ecology and negatively impact beneficial organisms. Maintain proper orchard sanitation by removing fallen leaves, pruning dead or diseased branches, and controlling weed growth to reduce disease inoculum and pest habitat.'
    },
    {
        image: 'images/applerust.jpg',
        name: 'Apple Rust',
        description: 'Apple rust is a fungal disease that causes orange rust spots on leaves and fruit, often spread by nearby juniper plants. This disease can lead to defoliation, reduced fruit yield, and overall decline in apple tree health if left untreated.',
        symptoms: 'Symptoms of apple rust include the formation of orange to rusty-brown spots or lesions on the upper surfaces of apple leaves. These spots may appear raised or blister-like and can coalesce to cover large areas of leaf tissue. As the disease progresses, infected leaves may become distorted, curled, or drop prematurely. In severe cases, rust-infected fruits may develop raised lesions or deformities, resulting in reduced fruit quality and marketability.',
        causes: 'Apple rust is caused by fungal pathogens belonging to the Gymnosporangium genus, which require both apple and juniper hosts to complete their life cycle. The disease spreads through airborne spores produced on infected juniper plants during wet weather conditions. These spores can travel long distances and infect nearby apple trees, especially during periods of prolonged leaf wetness or rainfall, leading to apple rust outbreaks in orchards located near juniper habitats.',
        management: 'Management of apple rust involves implementing cultural, biological, and chemical control measures to suppress fungal spore production and prevent disease spread. Cultural practices such as removing nearby juniper hosts, planting resistant apple varieties, and maintaining good orchard sanitation can help reduce disease pressure. Biological control agents, such as beneficial fungi or bacteria, may also be employed to inhibit rust pathogen growth. Additionally, chemical control options using fungicides like myclobutanil or mancozeb can effectively manage apple rust outbreaks when applied according to label instructions and integrated into a comprehensive disease management program.',
        medicines: 'To control apple rust, apply fungicides like myclobutanil or mancozeb according to recommended dosage and timing. These fungicides can help suppress fungal spore production and prevent further spread of the disease within the apple orchard.',
        precautions: 'To minimize the risk of apple rust outbreaks, remove and destroy nearby juniper hosts to eliminate potential sources of fungal inoculum. Prune infected apple branches to remove diseased tissue and reduce disease spread within the orchard. Implement timely fungicide applications during periods of high disease pressure, such as early spring when apple trees are most susceptible to rust infection. Additionally, consider planting apple varieties with natural resistance to rust pathogens to reduce the need for chemical treatments and minimize disease risk.'
    },
    {
        image: 'images/applescap.jpg',
        name: 'Apple Scab',
        description: 'Apple scab is a fungal disease that causes dark, scabby lesions on apples and leaves, leading to significant fruit loss and reduced orchard productivity. This disease is caused by the fungus Venturia inaequalis and thrives in cool, wet conditions, making apple orchards susceptible to scab outbreaks during periods of spring rain and high humidity.',
        symptoms: 'Symptoms of apple scab include the development of olive-green to black lesions on the leaves, fruits, and twigs of apple trees. These lesions may initially appear as small, circular spots that gradually enlarge and become sunken and velvety in texture. Infected leaves may become distorted or curled, and heavily affected fruits may exhibit cracking or deformation. Severe scab infections can lead to premature leaf drop, reduced fruit yield, and overall decline in apple tree health.',
        causes: 'Apple scab is caused by the fungus Venturia inaequalis, which overwinters on fallen leaves and fruit mummies in the orchard. In spring, fungal spores are released from overwintering structures and spread to new apple foliage and fruit during wet weather conditions. The disease thrives in cool, moist environments with prolonged leaf wetness, making apple orchards susceptible to scab outbreaks during periods of spring rain and high humidity.',
        management: 'Management of apple scab involves implementing integrated disease management strategies to minimize disease pressure and prevent fruit loss. Cultural practices such as pruning to improve air circulation, removing infected fruit and foliage, and maintaining proper orchard sanitation can help reduce disease inoculum and limit disease spread. Additionally, chemical control options using fungicides like captan or mancozeb can effectively suppress scab outbreaks when applied according to recommended dosage and timing.',
        medicines: 'To control apple scab, apply fungicides like captan or mancozeb according to recommended dosage and timing. These fungicides can help inhibit fungal growth and prevent further spread of the disease within the apple orchard.',
        precautions: 'To minimize the risk of apple scab outbreaks, rake and destroy fallen leaves and fruit mummies in the orchard to remove overwintering structures and reduce disease inoculum. Prune infected apple branches to remove diseased tissue and promote air circulation within the canopy. Implement timely fungicide applications during periods of high disease pressure, such as early spring when apple trees are most susceptible to scab infection. Additionally, consider planting apple varieties with natural resistance to scab pathogens to reduce the need for chemical treatments and minimize disease risk.'
    },
    {
        image: 'images/bananacordana.jpg',
        name: 'Banana Cordana',
        description: 'Banana cordana is a fungal disease that causes leaf spots and blight in banana plants, affecting their overall health and productivity. This disease can lead to defoliation, reduced fruit yield, and significant economic losses in banana cultivation.',
        symptoms: 'Symptoms of banana cordana include the development of irregularly shaped, dark brown to black spots or lesions on the leaves of banana plants. These spots may initially appear water-soaked or greasy and can coalesce to form large necrotic areas, ultimately causing leaf blight and premature leaf drop. Infected leaves may exhibit yellowing, wilting, or curling, and severely affected plants may experience stunted growth or dieback of foliage.',
        causes: 'Banana cordana is caused by fungal pathogens belonging to the Cordana genus, such as Cordana musae. The disease thrives in warm, humid conditions with poor air circulation, making banana plantations susceptible to cordana outbreaks during periods of high humidity or rainfall. Fungal spores are spread through splashing water, wind, or contact with contaminated tools, equipment, or plant debris, facilitating disease transmission within the plantation.',
        management: 'Management of banana cordana involves implementing cultural, biological, and chemical control measures to suppress fungal growth and prevent disease spread. Cultural practices such as maintaining proper spacing between banana plants, removing infected leaves and plant debris, and improving air circulation within the plantation can help reduce disease pressure. Biological control agents, such as beneficial fungi or bacteria, may also be employed to inhibit cordana pathogen growth. Additionally, chemical control options using fungicides like mancozeb or chlorothalonil can effectively manage cordana outbreaks when applied according to label instructions and integrated into a comprehensive disease management program.',
        medicines: 'To control banana cordana, treat affected plants with fungicides like mancozeb or chlorothalonil according to recommended dosage and timing. These fungicides can help suppress fungal growth and prevent further spread of the disease within the banana plantation.',
        precautions: 'To minimize the risk of banana cordana outbreaks, remove and destroy affected leaves and plant debris promptly to reduce disease inoculum and prevent disease spread within the plantation. Maintain proper spacing between banana plants to improve air circulation and reduce humidity levels, as excessive moisture promotes fungal growth and disease development. Implement good drainage practices to prevent waterlogging and minimize environmental conditions favorable for cordana pathogens. Regularly inspect banana plants for signs of cordana infection and implement timely interventions to prevent disease establishment and spread.'
    },
    {
        image: 'images/bananahealthy.jpg',
        name: 'Banana Healthy',
        description: 'Banana healthy refers to the optimal state of banana plants where they grow vigorously without exhibiting any signs of diseases or pest infestations. In this condition, banana plants produce high-quality fruits and maintain overall plantation productivity, contributing to successful banana cultivation.',
        symptoms: 'Symptoms of healthy banana plants include lush green foliage, robust stems, and vigorous growth throughout the growing season. The absence of any abnormal discoloration, lesions, or deformities on the leaves, pseudostems, or fruits indicates the plants health. Healthy banana plants typically exhibit balanced vegetative and reproductive growth, with consistent fruit development and yield.',
        causes: 'Banana plants achieve and maintain a healthy state when provided with optimal growing conditions, including sufficient sunlight exposure, well-drained soil, adequate moisture levels, and appropriate nutrient availability. Healthy banana plantations also benefit from good agricultural practices such as balanced fertilization, regular irrigation, and integrated pest management strategies to prevent disease and pest outbreaks.',
        management: 'Maintaining banana plant health requires proactive monitoring, preventive measures, and timely interventions to address any emerging issues before they escalate into significant problems. Regular inspections of banana plants for signs of diseases, pests, or nutrient deficiencies allow growers to detect and mitigate potential threats early. Implementing standard agricultural practices such as balanced fertilization, proper irrigation scheduling, and weed control helps support banana plant health and vigor throughout the growing season.',
        medicines: 'No specific treatments are needed for healthy banana plants. However, routine applications of balanced fertilizers, micronutrient supplements, and organic soil amendments can promote plant vigor and enhance fruit quality. Additionally, preventive measures such as the use of disease-resistant banana varieties and the implementation of phytosanitary measures help minimize the risk of disease and pest infestations in banana plantations.',
        precautions: 'To maintain the health of banana plants, follow good agricultural practices including balanced fertilization, regular irrigation, and weed control. Implement integrated pest management strategies to prevent pest outbreaks and minimize pesticide use, which can negatively impact beneficial organisms and environmental health. Monitor banana plants regularly for signs of diseases, pests, or nutrient deficiencies, and take prompt action to address any issues before they escalate.'
    },
    {
        image: 'images/bananapestalotiopsis.jpg',
        name: 'Banana Pestalotiopsis',
        description: 'Banana pestalotiopsis is a fungal disease that causes spots and rot on banana leaves and fruit, leading to significant yield losses and reduced fruit quality. This disease can affect various stages of banana growth, from seedling to mature fruit, and poses a considerable threat to banana cultivation worldwide.',
        symptoms: 'Symptoms of banana pestalotiopsis include the development of brown to black spots or lesions on the leaves, pseudostems, and fruit of banana plants. These spots may initially appear water-soaked or sunken and can expand rapidly to cover large areas of tissue, resulting in leaf blight, stem cankers, or fruit rot. Infected leaves may exhibit yellowing, wilting, or necrosis, and severely affected plants may experience defoliation or dieback of foliage.',
        causes: 'Banana pestalotiopsis is caused by fungal pathogens belonging to the Pestalotiopsis genus, such as Pestalotiopsis spp. The disease thrives in warm, humid conditions with poor air circulation, making banana plantations susceptible to pestalotiopsis outbreaks during periods of high humidity or rainfall. Fungal spores are spread through wind, water, or contact with contaminated tools, equipment, or plant debris, facilitating disease transmission within the plantation.',
        management: 'Management of banana pestalotiopsis involves implementing cultural, biological, and chemical control measures to suppress fungal growth and prevent disease spread. Cultural practices such as maintaining proper spacing between banana plants, removing infected leaves and plant debris, and improving air circulation within the plantation can help reduce disease pressure. Biological control agents, such as beneficial fungi or bacteria, may also be employed to inhibit pestalotiopsis pathogen growth. Additionally, chemical control options using fungicides like benomyl or thiophanate-methyl can effectively manage pestalotiopsis outbreaks when applied according to label instructions and integrated into a comprehensive disease management program.',
        medicines: 'To control banana pestalotiopsis, treat affected plants with fungicides like benomyl or thiophanate-methyl according to recommended dosage and timing. These fungicides can help suppress fungal growth and prevent further spread of the disease within the banana plantation.',
        precautions: 'To minimize the risk of banana pestalotiopsis outbreaks, ensure proper drainage and avoid waterlogging in the plantation to prevent favorable conditions for fungal growth and disease development. Remove and destroy affected leaves and plant debris promptly to reduce disease inoculum and prevent disease spread within the plantation. Maintain proper spacing between banana plants'
    },    
    {
        image: 'images/bananasigatoka.jpg',
        name: 'Banana Sigatoka',
        description: 'Banana Sigatoka is a major fungal disease that affects banana plants, causing streaks on leaves and reducing fruit yield. It is one of the most economically significant diseases affecting banana cultivation worldwide.',
        symptoms: 'Symptoms of Banana Sigatoka include the development of yellow to brown streaks or lesions on the leaves of banana plants. These streaks may initially appear water-soaked or greasy and can expand rapidly to cover large areas of leaf tissue. Infected leaves may exhibit yellowing, wilting, or curling, and severely affected plants may experience defoliation or dieback of foliage. Banana Sigatoka can also lead to reduced fruit yield and quality.',
        causes: 'Banana Sigatoka is caused by fungal pathogens belonging to the Mycosphaerella genus, including Mycosphaerella fijiensis and Mycosphaerella musicola. The disease thrives in warm, humid conditions with poor air circulation, making banana plantations susceptible to Sigatoka outbreaks during periods of high humidity or rainfall. Fungal spores are spread through wind, water, or contact with contaminated tools, equipment, or plant debris, facilitating disease transmission within the plantation.',
        management: 'Management of Banana Sigatoka involves implementing cultural, biological, and chemical control measures to suppress fungal growth and prevent disease spread. Cultural practices such as maintaining proper spacing between banana plants, removing infected leaves, and ensuring good plant spacing can help reduce disease pressure. Biological control agents, such as beneficial fungi or bacteria, may also be employed to inhibit Sigatoka pathogen growth. Additionally, chemical control options using fungicides like mancozeb or propiconazole can effectively manage Sigatoka outbreaks when applied according to label instructions and integrated into a comprehensive disease management program.',
        medicines: 'To control Banana Sigatoka, apply fungicides such as mancozeb or propiconazole according to recommended dosage and timing. These fungicides can help suppress fungal growth and prevent further spread of the disease within the banana plantation.',
        precautions: 'To minimize the risk of Banana Sigatoka outbreaks, regularly remove and destroy infected leaves to reduce disease inoculum and prevent disease spread within the plantation. Ensure good plant spacing and proper airflow within the plantation to reduce humidity levels and create less favorable conditions for fungal growth. Implement timely fungicide applications during periods of high disease pressure, such as early spring when banana plants are most susceptible to Sigatoka infection. Additionally, monitor banana plants regularly for signs of Sigatoka infection and implement preventive measures to prevent disease establishment and spread.'
    },
    {
        image: 'images/grapeblackrot.jpg',
        name: 'Grape Black Rot',
        description: 'Grape Black Rot is a fungal disease that affects grapevines, causing black, mummified berries and leaf spots. It is one of the most common and destructive diseases affecting grape cultivation worldwide, leading to significant yield losses and reduced fruit quality.',
        symptoms: 'Symptoms of Grape Black Rot include the development of black, sunken lesions or spots on grape berries and leaves. Infected berries may become mummified and shriveled, with dark, velvety fungal growth visible on the surface. Infected leaves may exhibit circular to irregular spots that gradually enlarge and coalesce, ultimately leading to defoliation and reduced vine vigor. Severe infections can result in premature berry drop, stunted vine growth, and overall decline in vineyard productivity.',
        causes: 'Grape Black Rot is caused by the fungus Guignardia bidwellii, which overwinters on infected plant debris and produces spores that are dispersed by wind or rain. The disease thrives in warm, humid conditions, making grapevines susceptible to black rot outbreaks during periods of wet weather or high humidity. Fungal spores can infect grape tissues through wounds, natural openings, or during fruit ripening, facilitating disease transmission and spread within the vineyard.',
        management: 'Management of Grape Black Rot involves implementing integrated disease management strategies to minimize disease pressure and prevent fruit loss. Cultural practices such as pruning to improve air circulation, removing infected plant parts, and maintaining good vineyard sanitation can help reduce disease inoculum and limit disease spread. Additionally, chemical control options using fungicides like myclobutanil or captan can effectively suppress black rot outbreaks when applied according to recommended dosage and timing.',
        medicines: 'To control Grape Black Rot, apply fungicides like myclobutanil or captan according to recommended dosage and timing. These fungicides can help inhibit fungal growth and prevent further spread of the disease within the vineyard.',
        precautions: 'To minimize the risk of Grape Black Rot outbreaks, prune and destroy infected plant parts, including mummified berries and diseased leaves, to remove disease inoculum and reduce disease spread within the vineyard. Maintain good vineyard sanitation by removing fallen leaves, weeds, and other plant debris that may harbor fungal spores or provide a conducive environment for disease development. Implement regular inspections of grapevines for signs of black rot infection and implement timely fungicide applications during critical growth stages to protect against disease establishment and spread.'
    },
    {
        image: 'images/grapehealthy.jpg',
        name: 'Grape Healthy',
        description: 'Grape Healthy refers to the optimal state of grapevines where they are free from diseases and pests, exhibiting healthy growth and productivity. In this condition, grapevines produce high-quality fruit and maintain overall vineyard performance, contributing to successful grape cultivation and wine production.',
        symptoms: 'Symptoms of healthy grapevines include vibrant green foliage, robust canes, and vigorous growth throughout the growing season. The absence of any abnormal discoloration, lesions, or deformities on the leaves, stems, or clusters indicates the plants health. Healthy grapevines typically exhibit balanced vegetative and reproductive growth, with consistent fruit set and development.',
        causes: 'Grapevines achieve and maintain a healthy state when provided with optimal growing conditions, including sufficient sunlight exposure, well-drained soil, adequate moisture levels, and appropriate nutrient availability. Healthy vineyards also benefit from good agricultural practices such as balanced fertilization, regular irrigation, and integrated pest management strategies to prevent disease and pest outbreaks.',
        management: 'Maintaining grapevine health requires proactive monitoring, preventive measures, and timely interventions to address any emerging issues before they escalate into significant problems. Regular inspections of grapevines for signs of diseases, pests, or nutrient deficiencies allow growers to detect and mitigate potential threats early. Implementing standard agricultural practices such as balanced fertilization, proper irrigation scheduling, and canopy management helps support grapevine health and vigor throughout the growing season.',
        medicines: 'No specific medicines are required for healthy grapevines. However, routine applications of balanced fertilizers, micronutrient supplements, and organic soil amendments can promote vine vigor and enhance fruit quality. Additionally, preventive measures such as the use of disease-resistant grape varieties and the implementation of phytosanitary measures help minimize the risk of disease and pest infestations in vineyards.',
        precautions: 'To maintain the health of grapevines, regularly inspect vines for signs of diseases, pests, or nutrient deficiencies, and take prompt action to address any issues before they escalate. Follow standard care practices, including proper pruning, trellising, and canopy management, to optimize vineyard health and productivity. Implement integrated pest management strategies to prevent pest outbreaks'
    },    
    {
        image: 'images/grapeleafblight.jpg',
        name: 'Grape Leaf Blight',
        description: 'Grape Leaf Blight is a fungal disease that affects grapevines, causing brown spots and leaf blight. It can lead to defoliation and reduced vineyard productivity if left untreated.',
        symptoms: 'Symptoms of Grape Leaf Blight include the development of brown spots or lesions on grape leaves, which may appear water-soaked or greasy. These spots can enlarge and coalesce, resulting in extensive leaf blight and premature leaf drop. Infected leaves may exhibit yellowing, wilting, or curling, and severely affected vines may experience defoliation or dieback of foliage. Grape Leaf Blight can also affect fruit quality and yield.',
        causes: 'Grape Leaf Blight is caused by fungal pathogens such as Phomopsis viticola or Guignardia bidwellii, which thrive in warm, humid conditions with poor air circulation. The disease spreads through wind, water, or contact with contaminated tools, equipment, or plant debris, facilitating disease transmission within the vineyard.',
        management: 'Management of Grape Leaf Blight involves implementing cultural, biological, and chemical control measures to suppress fungal growth and prevent disease spread. Cultural practices such as maintaining proper spacing between grapevines, removing infected leaves, and ensuring good air circulation can help reduce disease pressure. Biological control agents, such as beneficial fungi or bacteria, may also be employed to inhibit Leaf Blight pathogen growth. Additionally, chemical control options using fungicides like copper oxychloride or mancozeb can effectively manage Leaf Blight outbreaks when applied according to recommended dosage and timing.',
        medicines: 'To control Grape Leaf Blight, use fungicides like copper oxychloride or mancozeb according to recommended dosage and timing. These fungicides can help suppress fungal growth and prevent further spread of the disease within the vineyard.',
        precautions: 'To minimize the risk of Grape Leaf Blight outbreaks, ensure proper air circulation within the vineyard by avoiding overcrowding of vines and trellising systems. Avoid overhead watering, as wet foliage provides favorable conditions for disease development. Implement timely fungicide applications during periods of high disease pressure, such as early spring or after rainfall events. Regularly inspect grapevines for signs of Leaf Blight infection and remove and destroy infected leaves promptly to reduce disease inoculum and prevent disease spread within the vineyard.'
    },
    {
        image: 'images/guavahealthy.jpg',
        name: 'Guava Healthy',
        description: 'Guava Healthy refers to the optimal state of guava plants where they grow vigorously without showing signs of disease or pest infestations. In this condition, guava plants produce high-quality fruits and maintain overall orchard productivity, contributing to successful guava cultivation.',
        symptoms: 'Symptoms of healthy guava plants include lush green foliage, sturdy branches, and vigorous growth throughout the growing season. The absence of any abnormal discoloration, lesions, or deformities on the leaves, stems, or fruits indicates the plants health. Healthy guava plants typically exhibit balanced vegetative and reproductive growth, with consistent fruit development and yield.',
        causes: 'Guava plants achieve and maintain a healthy state when provided with optimal growing conditions, including proper sunlight exposure, well-drained soil, adequate moisture levels, and appropriate nutrient availability. Healthy orchards also benefit from good cultural practices such as regular pruning, proper spacing between trees, and integrated pest management strategies to prevent disease and pest outbreaks.',
        management: 'Maintaining guava plant health requires ongoing monitoring, preventive measures, and timely interventions to address any emerging issues before they escalate into significant problems. Regular inspections of guava plants for signs of diseases, pests, or nutrient deficiencies allow growers to detect and mitigate potential threats early. Implementing standard care practices such as balanced fertilization, irrigation management, and weed control helps support guava plant health and vitality throughout the growing season.',
        medicines: 'No specific treatments are needed for healthy guava plants. However, routine applications of balanced fertilizers, micronutrient supplements, and organic soil amendments can promote plant vigor and enhance fruit quality. Additionally, preventive measures such as the use of disease-resistant guava varieties and the implementation of phytosanitary measures help minimize the risk of disease and pest infestations in guava orchards.',
        precautions: 'To maintain the health of guava plants, maintain regular care practices, including proper watering, fertilization, and pruning. Monitor guava orchards regularly for signs of diseases, pests, or nutrient deficiencies, and take prompt action to address any issues before they escalate. Implement integrated pest management strategies to prevent pest outbreaks and minimize pesticide use, which can negatively impact beneficial organisms and environmental health.'
    },
    {
        image: 'images/guavaredrust.jpg',
        name: 'Guava Red Rust',
        description: 'Guava Red Rust is a fungal disease that affects guava plants, causing red, rust-like spots on leaves and fruit. It can lead to defoliation and reduced fruit yield if left untreated.',
        symptoms: 'Symptoms of Guava Red Rust include the development of red, rust-like spots or lesions on guava leaves and fruit. These spots may initially appear small and inconspicuous but can enlarge and coalesce, covering large areas of leaf tissue and fruit surface. Infected leaves may exhibit yellowing, wilting, or curling, and severely affected plants may experience defoliation or dieback of foliage. Guava Red Rust can also affect fruit quality and yield, leading to economic losses in guava cultivation.',
        causes: 'Guava Red Rust is caused by fungal pathogens such as Puccinia psidii, which thrive in warm, humid conditions with poor air circulation. The disease spreads through wind, water, or contact with contaminated tools, equipment, or plant debris, facilitating disease transmission within the orchard.',
        management: 'Management of Guava Red Rust involves implementing cultural, biological, and chemical control measures to suppress fungal growth and prevent disease spread. Cultural practices such as maintaining proper spacing between guava plants, removing infected leaves, and improving air circulation can help reduce disease pressure. Biological control agents, such as beneficial fungi or bacteria, may also be employed to inhibit Red Rust pathogen growth. Additionally, chemical control options using fungicides like copper oxychloride or mancozeb can effectively manage Red Rust outbreaks when applied according to recommended dosage and timing.',
        medicines: 'To control Guava Red Rust, treat affected plants with fungicides such as copper oxychloride or mancozeb according to recommended dosage and timing. These fungicides can help suppress fungal growth and prevent further spread of the disease within the guava orchard.',
        precautions: 'To minimize the risk of Guava Red Rust outbreaks, remove and destroy infected plant parts promptly to reduce disease inoculum and prevent disease spread within the orchard. Improve air circulation around guava plants by pruning overcrowded branches and ensuring proper spacing between trees. Implement timely fungicide applications during periods of high disease pressure, such as after rainfall events or during periods of warm, humid weather. Regularly inspect guava plants for signs of Red Rust infection and take preventive measures to prevent disease establishment and spread.'
    }
    
];


window.onload = function() {
    const searchBar = document.getElementById('searchBar');
    const diseaseContainer = document.getElementById('diseaseContainer');

    function displayDiseases(diseases) {
        diseaseContainer.innerHTML = '';
        diseases.forEach(disease => {
            const card = document.createElement('div');
            card.classList.add('disease-card');
            card.innerHTML = 
                ` <img src="${disease.image}" alt="${disease.name}">
                <h3>${disease.name}</h3>
                <p>${disease.description}</p>
            `;
            card.onclick = () => {
                const params = new URLSearchParams({
                    name: disease.name,
                    description: disease.description,
                    symptoms: disease.symptoms,
                    causes: disease.causes,
                    management: disease.management,
                    medicines: disease.medicines,
                    precautions: disease.precautions
                });
                window.location.href = `details.html?${params.toString()}`;
            };
            diseaseContainer.appendChild(card);
        });
    }

    
    displayDiseases(diseases);


    searchBar.oninput = function() {
        const searchTerm = searchBar.value.toLowerCase();
        const filteredDiseases = diseases.filter(disease => 
            disease.name.toLowerCase().includes(searchTerm)
        );
        displayDiseases(filteredDiseases);
    }
};
